<?php
declare(strict_types=1);

/** @var Template $block */
/** @var Santander $magewire */

/** @var Escaper $escaper */

use Snowdog\Hyva\Checkout\Santander\Payment\Method\Santander;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$issuers = $magewire->getIssuers();
?>
<div
    class="grid grid-cols-[auto,auto]"
    wire:payment-method="eraty_santander"
>
    <input
        class="cursor-pointer text-pink-700 mt-1"
        type="checkbox"
        checked
        name="accept_tos"
        id="accept_tos"
        wire:model="acceptTos"
    />
    <label for="accept_tos">
        <span>
            <?= $escaper->escapeHtml(
                __(
                    'I have familiarised myself with the procedure for granting consumer credit for the purchase of goods and services'
                )
            ) ?>
        </span>
        <a
            class="link link-secondary"
            target="_blank"
            href="https://www.santanderconsumer.pl/raty-jak-kupic"
        >
            <?= $escaper->escapeHtml(__('eRaty Santander Consumer Bank')) ?>
        </a>
    </label>
</div>
